language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true

reviews:
  review_status: false              # Show/hide review status messages
  high_level_summary: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: false
  related_issues: false
  related_prs: false
  poem: false
  commit_status: false
  fail_commit_status: false
  auto_review:
    enabled: true
    drafts: true

chat:
  auto_reply: true
  integrations:
    linear:
      usage: enabled
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []
